# Site settings
title: Portfolio - Louqou / Matt Butcher
description: Portfolio for Matt Butcher
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://louqou.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Matt Butcher
user_description: "Hello! I'm Matt, a Unity developer from Manchester, England. I've been using Unity for a couple of years now creating games, simulators, and fun side projects. Currently, I'm working in a two person indie team creating a game called Wizbox!"
user_title: Unity Developer
email: mattbutcher93@gmail.com
twitter_username: louqou1
github_username: Louqou
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
