# Site settings
title: Portfolio - Louqou / Matt Butcher
description: Portfolio for Matt Butcher
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://louqou.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Matt Butcher
user_description: Hello
user_title: Game Developer
email: mattbutcher93@gmail.com
twitter_username: louqou1
github_username: Louqou
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
